### ISSUE TITLE
LCD and Battery models

### ISSUE THREAD

**Issue by arturo182** [cutiepi-io/cutiepi-board#11]
I might've missed it somewhere, but I think there is no info on the LCD and the battery part numbers and/or links?

**Comment by penk** [comment]
Hi @arturo182 , (btw, big fan of your keyboard featherwing works :-)

We supported/tested two MIPI DSI displays: 
1. AML080WXBI3103S (https://www.amelin.com.cn/h-pd-104.html)
2. TXW800018S0-LSS (http://www.txwlcd.cn/en/h-pd-437.html#fai_14_top&pfc=&_pp=0_35) 

The former one uses a `JD9366` controller, and the later one uses `ILI9881C`. You can find the out-of-tree drivers here: https://github.com/cutiepi-io/cutiepi-drivers#mipi-display 

As for battery, any 3.7V li-po battery goes. We found a 5259109 one that best fits the case. Unfortunately the vendor does not sell sample on aliexpress/taobao.
