### ISSUE TITLE
Export the brd and schematic files to be compatible with eagle or kicad

### ISSUE THREAD

**Issue by rahmanshaber** [cutiepi-io/cutiepi-board#12]
Most of us don't have Cadence software, if possible export the files to a universal file so everyone can make use of it. also if possible a separate library file that includes all the parts used in the design.
thanks.

**Comment by boelle** [comment]
same here... i wanted to see how much i could remove and if it would make sense

ie i dont need the camera or the 2 mic's, nor the ports other than charging

pdf's are ok'ish, but yeah kicad (free) would have been nice

**Comment by penk** [comment]
Close as duplicate to issue #9, please see my comment there. Thank you!
