### ISSUE TITLE
USB C changing cannot be pulled out.

### ISSUE THREAD

**Issue by usstlf** [cutiepi-io/cutiepi-board#15]
The MP2636GR can not full fill requirement of CM4.
CM4 works between 4.75 to 5.25 V.
If the USB C is plugged in then pulled out. 
The MP2636GR can first start the boost of battery when the voltage dropped to battery voltage + 300mv.
This will cause the CM4 shut down.
we found a temporary solution for this, change the R3092 to 3k, it will solve the problem.
But the resistor must be very precision. above 3.3k or below 2.7k will not solve this problem.
We afraid that the tk of resistor will also impact the reliability of the pad.
But we didn't have further test.

**Comment by penk** [comment]
Hi @usstlf, thank you for the report, we solved this issue by 1) changing R3092 to 3k, and 2) adding one 10V/220uF capacitor at C2505 in parallel. The latest BOM should reflects that change.
